### ISSUE TITLE
New Template shows erroneous menu 

### ISSUE THREAD

**Issue by 88kbbq** [getgrav/grav-plugin-devtools#1]
Still learning but just created a new template and see the site has menu items "Features", "Pricing", "Screenshots", etc. Where do these come from? I don't have any pages with these names and can't find these words anywhere in the template code base. ~~Not only that, but of the two pages I do have saved, only the home pages shows on the front end.~~ Advice?

**Comment by rhukster** [comment]
How did you create the theme? and what is in your user/pages folder?

**Comment by 88kbbq** [comment]
user/pages shows just 01.home and 02.menu, like I set them up for ordering. Folders contain only default.en.md and default.tw.md, but then I see an image I uploaded to the page. Wonder why that wasn't saved in the themes/my-theme/images folder. Stumped. Cleared cache, restarted services, cleared browser cache. grav.88k.com.tw

**Comment by 88kbbq** [comment]
Found a /user/config/site.yaml with all those menu items. Sorry, didn't think to search the whole code base, only templates. Will read up on how to use this site.yaml file.
