### ISSUE TITLE
new scss folder 

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-plugin-devtools#10]
as a feature, besides the new css folder, ther could be an option to create a scss/sass folder with a custom.scss / sass file that can be complied to the already existing custom.css in the css folder ?

**Comment by rhukster** [comment]
The intention is really just to create the basic theme framework, the choice of SCSS or LESS or anything else is really something that depends on the direction the theme takes.  This plugin is intended to setup the core stuff that Grav requires for a theme to work, but really not too much with the theme itself.

**Comment by KrakenEXE** [comment]
Update on this.

**Comment by rhukster** [comment]
Already explained this is not the intention of this plugin.  It's more to create the skeleton files.  The actual theme is intended to be very basic without design decisions imposed upon the user.
