### ISSUE TITLE
error when creating new theme

### ISSUE THREAD

**Issue by staspih** [getgrav/grav-plugin-devtools#11]
When you create a new theme, an error is displayed:

`...Please choose a template type
  [0] pure-blank
  [1] inheritence
 > PHP Notice:  Undefined variable: output in /var/www/.../vendor/symfony/console/Helper/QuestionHelper.php on line 449
PHP Notice:  Undefined variable: exitcode in /var/www/.../vendor/symfony/console/Helper/QuestionHelper.php on line 449
PHP Warning:  exec() has been disabled for security reasons in /var/www/.../vendor/symfony/console/Helper/QuestionHelper.php on line 449
PHP Notice:  Undefined variable: exitcode in /var/www/.../vendor/symfony/console/Helper/QuestionHelper.php on line 451...`

But the theme is created, nothing unusual. What could be the problem?
Thanks

**Comment by flaviocopes** [comment]
It's just a warning, could be an upstream issue in the `symfony/console` package. I checked, seems nothing bad.
