### ISSUE TITLE
Update pure to https CDN

### ISSUE THREAD

**Issue by cubiq** [getgrav/grav-plugin-devtools#16]
Very small thing, but... latest Pure release https://unpkg.com/purecss@0.6.2/build/pure-min.css (please note HTTPS)

**Comment by KrakenEXE** [comment]
I'll take care of this.

**Comment by KrakenEXE** [comment]
@rhukster I need permission to push to this repository so that I can submit a Pull Request. This is my first open source project I've committed to so if I make mistakes please let help me learn.

**Comment by Vivalldi** [comment]
@KrakenEXE fork the repo and then you can make a pull request from your repo

**Comment by KrakenEXE** [comment]
completed.
