### ISSUE TITLE
pure-blank theme not visible

### ISSUE THREAD

**Issue by DevBowser** [getgrav/grav-plugin-devtools#20]
After installing the devtools and running the command via the CLI to create a new pure-blank theme I run into the following error:

`Notice: Undefined index: bpname in C:\xampp\htdocs\kn\user\plugins\devtools\classes\DevToolsCommand.php on line 83`

When checking via the Admin dashboard, the theme is simply not visible at all.

This is based on a clean installation of grav-admin-v1.3.4.
These are the steps I have taken to reproduce this error twice:

- Installing the latest updates from the Admin Dashboard
- Installing the DevTools official plugin in my CLI.
- Select pure-blank theme
- Prompt a name with no uppercases or any special characters

After the 2nd attempt with a clean installation I did notice how it prompted:
`SUCCESS theme antimatter -> Created Successfully` which seems rather confusing as antimatter is present by default.

Downloading and manually installing the 1.5 version of the DevTools plugin solved the issue **(for now)**.

**Comment by rhukster** [comment]
Fixed and released.
