### ISSUE TITLE
new-theme assumes I'll be publishing the theme on GitHub

### ISSUE THREAD

**Issue by JohnMH** [getgrav/grav-plugin-devtools#22]
Homepage, bugs, and readme are all set to a GitHub URL based on... my real name.

**Comment by rhukster** [comment]
Grav's GPM only support GitHub, so this is expected.

**Comment by JohnMH** [comment]
Perhaps support for other git hosts should be added? There is no reason to require the use of a centralized service.

**Comment by JohnMH** [comment]
That said, at least it does ask for 'GitHub ID' now instead of attempting to get it from my user's name. Major improvement.
