### ISSUE TITLE
`readme` vs `docs`

### ISSUE THREAD

**Issue by Perlkonig** [getgrav/grav-plugin-devtools#3]
In the scaffolding the `new-plugin` command creates, the `blueprints.yaml` file has a `readme` field but the plugin system actually pulls from the `docs` field. Is this a problem with how the plugin page is displaying things (e.g., I couldn't find `readme` or `docs` in the sample plugin blueprints)? Or should the plugin change the boilerplate? Thanks!

**Comment by Vivalldi** [comment]
I'm not sure I fully understand the question. 

The admin plugin picks up the README file created by the plugin if you have pushed it to github. As you can see [here](https://github.com/getgrav/grav-plugin-devtools/blob/develop/components/plugin/blank/blueprints.yaml.twig#L12) the read location is generated based on a fairly common pattern

**Comment by w00fz** [comment]
Actually you are right, the property should be `docs` in the template blueprint as that's what our repository generator understands and what triggers the Docs button to appear in our Plugins download section.

It looks like we have it wrong in the admin plugin which I believe was used for reference when creating the scaffolding one.

Fixing.
