### ISSUE TITLE
Wrong folder name: components/theme/inheritence/

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-plugin-devtools#32]
When creating new theme  using inheritance, plugin devtools tries to copy folder `components/theme/inheritance/` but folder is actually named `components/theme/inheritence/`

**Comment by pamtbaau** [comment]
Cross-posted in repository Grav issue [2131](https://github.com/getgrav/grav/issues/2131)

**Comment by rhukster** [comment]
Fixed.. thanks.
