### ISSUE TITLE
Object of class Grav\Plugin\DevToolsPlugin could not be converted to string

### ISSUE THREAD

**Issue by drzraf** [getgrav/grav-plugin-devtools#36]
I need to dump `Grav::instance()` to find the information I'm looking for. `Kint` is usually helpful in such a drupal-ish situation. But it's not possible:
```
require_once('/usr/local/bin//kint.phar');
\Kint::dump(Grav::instance());
```
Not sure whether or not `DevToolsPlugin` is the unique plugin that block Kint from dumping `Grav::instance()`

**Comment by rhukster** [comment]
You don't need Kint, you can simply use `dump()` which will use Syfony's VarDumper

**Comment by drzraf** [comment]
Indeed, it's far better...
Thank you
