### ISSUE TITLE
"bin/gpm install devtools" command throws "Permission denied"

### ISSUE THREAD

**Issue by maliyshock** [getgrav/grav-plugin-devtools#38]
Even with the 755 folder access rights.

The reason of it - you should use `php bin/gpm install devtools` instead of `bin/gpm install devtools`

**Comment by rhukster** [comment]
Only on your setup, where PHP is not in your path. Easier to add your PHP binary to your path, and never have to prefix the commands.

**Comment by maliyshock** [comment]
Yes, but the thing is - it is not obvious. And there are no hints in the documentation. At least I haven't seen them.
Could you please add a notice in the docs? It might save time for others. For example for someone like me, who was confused.

**Comment by rhukster** [comment]
I’ve made a note to better document this.
