### ISSUE TITLE
Declaration of theme_config removed in base.html.twig, but not in navigation.html.twig

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-plugin-devtools#45]
In theme `pure-blank`, the definition of `theme_config` has been removed at line 1 of `base.html.twig`, but is still used in `navigation.html.twig`:
```
line 26: {% if theme_config.dropdown.enabled %}
```

Either re-define `theme_config`, or change `navigation.html.twig` to use `config.theme` or `theme` to access its properies.

**Comment by rhukster** [comment]
Fixed in develop

**Comment by pamtbaau** [comment]
Thanks rhukster!
