### ISSUE TITLE
Clarify user should cd into folder of plugin before running 'composer update'

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-plugin-devtools#61]
After creating a new plugin, devtools notes: "Make sure to run `composer update` to initialize the autoloader".

This is probably confusing to users not familiar with composer and could be formulated more clearly. Since devtools already knows the name of the new plugin, it could be:

> Make sure to `$ cd user/plugins/<plugin name>` into the folder of the new plugin and run `$ composer update` to initialize the autoloader

**Comment by hughbris** [comment]
Should this be closed? Addressed in 68afa594 I think.
