### ISSUE TITLE
Typo in phpdoc in generated plugin?

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-plugin-devtools#66]
Is `*is` a typo? If not, what does it mean?

https://github.com/getgrav/grav-plugin-devtools/blob/3a82bc0c3a129c05048f80bd649bfdd3b7c16231/components/plugin/blank/plugin.php.twig#L34-L38

By the way, the indentation of lines 35, 36, 37 are off... Yes, I know, I'm nitpicking...

**Comment by mahagr** [comment]
Be free to fix them in a pull request :)

**Comment by pamtbaau** [comment]
I don't know if "*s" is a typo or has some meaning I'm not aware of....

**Comment by mahagr** [comment]
It is a typo, doesn't make any sense...

**Comment by jgonyea** [comment]
I don't think this typo exists anymore.  It was fixed in commit #9fd67d1.
