### ISSUE TITLE
"Typhoon CustomizedCustomized" bug

### ISSUE THREAD

**Issue by key-notes** [getgrav/grav-plugin-devtools#69]
Just noticed what appears to be a minor bug. When copying the Typhoon theme to "Typhoon customized", the backend strangely calls it "Typhoon CustomizedCustomized" – see screenshot.

Here's the output from the terminal where I entered "customized" only once:

`$ bin/plugin devtools new-theme`

`Enter Theme Name:`
`Typhoon customized`

**Comment by rhukster** [comment]
I can confirm i see this happening.
