### ISSUE TITLE
"New" is a reserved keyword

### ISSUE THREAD

**Issue by mirorauhala** [getgrav/grav-plugin-devtools#7]
"New" is a reserved keyword in PHP and it is not the only one.

When running command:

```
$ sudo bin/plugin devtools newtheme
Enter Theme Name: new
Enter Theme Description: asd
Enter Developer Name: John Doe
Enter Developer Email: john@doe.com
Please choose a template type
  [0] pure-blank
  [1] inheritance
> 0

SUCCESS theme new -> Created Successfully

Path: /var/www/grav-admin/user/themes/new
```

The error arises after you set the theme active and reload the blog (admin-side not affected).

``` php
ParseError syntax error, unexpected 'New' (T_NEW), expecting identifier (T_STRING)
```

This is caused because the theme's name is "new" and devtools automagically creates all files necessary.

Within the `user/themes/new` folder there will be a `new.php` that contains the line

``` php
class New extends Theme 
```

As said in [php.net](http://php.net/manual/en/reserved.keywords.php).

> You **cannot** use any of the following words as constants, class names, function or method names. Using them as variable names is generally OK, but could lead to confusion.
> 
> As of PHP 7.0.0 these keywords are allowed as property, constant, and method names of classes, interfaces and traits, except that class may not be used as constant name.

---

There should be some sort of prevention when using any of the keywords listed at [php.net](http://php.net/manual/en/reserved.keywords.php).

**Comment by w00fz** [comment]
Good catch! Yes we should have a list of reserved words that shouldn't be allowed.
I would think also a minimum length of characters allowed, for instance 3 is quite short but I think it is ok as the minimum allowed.
