### ISSUE TITLE
Tailwind theme created by devtools plugin is broken? 

### ISSUE THREAD

**Issue by tauchvogel** [getgrav/grav-plugin-devtools#78]
Hi there,

I play around with Grav CMS and its plugin dev tools. With this plugin I had successfully created a theme with tailwind.

I am a bit confused about a thing with this theme. In the “head” of the page I can see this code:
`<link rel="icon" type="image/png" href="/user/themes/taily/images/logo.png" />`

I can click on the link and I see the Grav-logo in a new browser window.

But I can not see this image on the page itself. Why?

The code in base.html.twig of the image is this:
`<link rel="icon" type="image/png" href="{{ url('theme://images/logo.png')|e }}" />`

Also the whole page output seems not working right now. It seems that the stylesheet is not loading exactly!

Is the theme broken? Please fix it, I wanna use it for Grav CMS!

**Comment by pamtbaau** [comment]
I think a new release must be created. The issue has been repaired in [commit #99376f8](https://github.com/getgrav/grav-plugin-devtools/commit/99376f8ba36db5a24463792b932c00c046948ba5) dating March 2022, while the latest release dates from Oct 2021.

**Comment by rhukster** [comment]
1.6.0 has now been released

**Comment by tauchvogel** [comment]
Actually the theme is still broken if I create it with devtools!

**Comment by pamtbaau** [comment]
@tauchvogel, 

- Image:
The code `<link rel="icon" type="image/png" href="{{ url('theme://images/logo.png')|e }}" />` inside `<head>` should only show a logo in the tab of the page. Not inside the the body of the page.
- Stylesheets: 
You're correct. After running the following scripts,  */user/themes/&lt;yourtheme>/dist/css/**site**.css*  is being created, while the template tries to load ***app**.css*. I thought it was changed in the PR.
  ```
  $ cd user/themes/yourtheme
  $ npm install
  $ npm run build
  ```

In the meantime, change
```
{% do assets.addCss('theme://dist/css/app' ~ extension ~ '.css', 98) %}
```
into 
```
{% do assets.addCss('theme://dist/css/site' ~ extension ~ '.css', 98) %}
```

**Comment by pamtbaau** [comment]
@tauchvogel,

Image:
Codeline `<link rel="icon" type="image/png" href="{{ url('theme://images/logo.png')|e }}" />` only adds a small icon to the tab of the browser. It does not add an image to the page itself.

Stylesheet:
- Did you upgrade plugin DevTools to the latest 1.6.0 version? The template now add the correct css file.

**Comment by tauchvogel** [comment]
I am using version 1.6.0 if devtools. No custom styling. Only theme css. It is still broken.

**Comment by pamtbaau** [comment]
@tauchvogel,  Define "broken"

**Comment by tauchvogel** [comment]
When I create a different theme via devtools, I see the page "normally". Everything is in its place. 

However, the Tailwind theme looks like some stylesheets are not loading properly (see screenshot).

The header is not there and the indentations are missing. Other styling is also missing or not loading.

<img width="1433" alt="Bildschirmfoto 2022-12-29 um 20 16 35" src="https://user-images.githubusercontent.com/19515246/210000797-7e0382de-5c14-4830-a078-bb83018c5f6f.png">

**Comment by pamtbaau** [comment]
> However, the Tailwind theme looks like some stylesheets are not loading properly (see screenshot).

Looking at your screenshot, it does indeed seems like the stylesheet from */user/themes/yourtheme/dist/site.css* has not been loaded. Did you run the following shell scripts which will generate file */user/themes/yourtheme/dist/site.css*:
```
$ cd user/themes/yourtheme
$ npm install
$ npm run watch
```

> The header is not there and the indentations are missing. Other styling is also missing or not loading.

Please be aware that the generated Tailwind theme is quite rudimentary. The template barely uses Tailwind utility classes nor does it provide any custom css, which means you'll have to provide these yourself.
