### ISSUE TITLE
inherited theme is after new theme

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-plugin-devtools#9]
when using the cmd line to create a new theme with inheritance, the new theme appears before the inherited theme in the new-theme.yaml thus rendering all modifications / css/twig/etc... useless ..

**Comment by rhukster** [comment]
well that's not good! :) should just be a matter of adjusting the template..

**Comment by rhukster** [comment]
Ack missed this for last release, will release again.

**Comment by hughbris** [comment]
Reminder to push this into next release please @rhuk, just got bit by it and lost some time and cranial follicle before realising it was a bug! :) At least I don't have to create an issue/PR, thanks @JohnMica

**Comment by hughbris** [comment]
Bump! https://discourse.getgrav.org/t/theme-inheritance-not-working-properly/5822
